### ISSUE TITLE
not able to see any of mine accounts , any ideas why ?

### ISSUE THREAD

**Issue by michaelm-88** [rmatec/aws-account-switcher-safari-extension#2]
![image](https://user-images.githubusercontent.com/69640345/108221798-1636ef80-7130-11eb-9f58-278244513152.png)
not able to see any of mine accounts , any ideas why ?

**Comment by michaelm-88** [comment]
my configuration is include about 55 accounts 
on Firefox  

![image](https://user-images.githubusercontent.com/69640345/108223032-4763ef80-7131-11eb-8c02-03f31603fef1.png)

**Comment by rmatec** [comment]
Hi,

Does reducing the number of accounts help? I am thinking this might be related to https://github.com/rmatec/aws-account-switcher-safari-extension/issues/1

**Comment by ghost** [comment]
Looks like reducing the number of accounts to below 60 seems to work but for me I need more. Any idea on how to resolve?

**Comment by rmatec** [comment]
I need to into the code and see what I can do. I'll try to find some time to do it. Unfortunately I do not have much free time these days.

**Comment by michaelm-88** [comment]
@rmatec  and @digeratidad  and yes ,  just notice I have some old accounts into my config thought was 57 but was 62 ,
 drop it to 55 and it is works
