### ISSUE TITLE
Available in Canada App Store? 🇨🇦 

### ISSUE THREAD

**Issue by mwarkentin** [rmatec/aws-account-switcher-safari-extension#6]
Hi, I was wondering if the extension is available in Canada 🇨🇦? When I open the App Store link in the readme I get an error:

```
App Not Available

This app is currently not available in your country or region.
```

**Comment by rmatec** [comment]
> Hi, I was wondering if the extension is available in Canada 🇨🇦? When I open the App Store link in the readme I get an error:
> 
> 
> 
> ```
> 
> App Not Available
> 
> 
> 
> This app is currently not available in your country or region.
> 
> ```

Hi,

The extension is no longer available in the AppStore because I no longer have a developer account. The subscription run out and I do no longer need it.
However, you can clone the xcode project and install the extension from there.

**Comment by antoinediev** [comment]
Hi,
Do we need a developer account to install the extension locally ?

**Comment by rmatec** [comment]
I think you can do that with the free tier.

**Comment by parkeyparker** [comment]
@rmatec do you mind if I publish my fork that I raised a PR for? I have an active developer account and don't mind keeping it up to date but I would like your permission before doing so as you put in the hard work getting everything setup initially and I've just updated things. I would of course give you credit as well as the main plugin author.

**Comment by rmatec** [comment]
> @rmatec do you mind if I publish my fork that I raised a PR for? I have an active developer account and don't mind keeping it up to date but I would like your permission before doing so as you put in the hard work getting everything setup initially and I've just updated things. I would of course give you credit as well as the main plugin author.

By all means, go ahead and publish it.

**Comment by parkeyparker** [comment]
@mwarkentin I've just hit publish so hopefully it should be available in your region for both MacOS and iOS here: https://apps.apple.com/gb/app/aws-extend-switch-roles/id1592710340

**Comment by mwarkentin** [comment]
Awesome, thanks!
